name: ML App CI

on:
  push:
    paths:
      - 'text-parsing-app/**'
  pull_request:
    paths:      
      - 'text-parsing-app/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Updated to the latest LTS version as of my last training cut-off

      - name: Package install
        run: npm install --legacy-peer-deps # Modified to handle peer dependencies if any

      - name: App build
        run: |
          cd text-parsing-app
          npm run build  # Fixed typo from mpm to npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3 bucket
        env:
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        run: aws s3 sync text-parsing-app/build s3://$S3_BUCKET_NAME/ --delete # Updated the build directory path
